name: CICD

on: [push]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        id: docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          workdir: context
          name: flowbrew/builder
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Show outputs of previous step
        run: |
          echo "tag $VAR1"
          echo "snapshot-tag $VAR2"
        env:
          VAR1: ${{ steps.docker.outputs.tag }}
          VAR2: ${{ steps.docker.outputs.snapshot-tag }}
